Feature/project set up
IFRCGo/montandon-etl pull request #2
Opened 2024-11-14 05:53 UTC by Rup-Narayan-Rajbanshi

## Changes
  - Set up project

## This PR doesn't introduce any:

- [ ] temporary files, auto-generated files or secret keys
- [ ] n+1 queries
- [ ] flake8 issues
- [ ] `print`
- [ ] typos
- [ ] unwanted comments

## This PR contains valid:

- [ ] tests
- [ ] permission checks (tests here too)
- [ ] translations

2024-11-14 09:09 UTC, thenav56 requested changes
Looks good. Few minor changes

2024-11-14 09:09 UTC, thenav56 commented on Dockerfile
> +ENV PYTHONUNBUFFERED 1
```suggestion
ENV PYTHONUNBUFFERED=1
```

2024-11-14 09:09 UTC, thenav56 commented on main/settings.py
> +    DJANGO_DEBUG=(bool, True),
```suggestion
    DJANGO_DEBUG=(bool, False),
```

2024-11-14 09:09 UTC, thenav56 commented on main/settings.py
> +        "ENGINE": "django.db.backends.postgresql",
We will need to install postgis.
https://docs.djangoproject.com/en/5.1/ref/contrib/gis/tutorial/#configure-settings-py

2024-11-14 09:09 UTC, thenav56 commented on scripts/run_develop.sh
> +python manage.py migrate &
Let's not add migrate here, let's add it to readme instead.

As migrate command can be destructive, it is a good idea to do this manually :D

2024-11-14 09:39 UTC, Rup-Narayan-Rajbanshi commented on main/settings.py
> +        "ENGINE": "django.db.backends.postgresql",
@thenav56 I think we need to update in docker-compose.yml for db image as `postgis/postgis:12-3.5-alpine⁠` as well.

2024-11-14 14:46 UTC, susilnem requested changes
Looks good.
Let's add a separate `.python-version` file for the python version which is `3.12`

2024-11-14 14:46 UTC, susilnem commented on Dockerfile
> +    && pip uninstall -y poetry virtualenv-clone virtualenv \
Let's add this one too
```suggestion
    && rm -rf /root/.cache/pypoetry \
    && pip uninstall -y poetry virtualenv-clone virtualenv \
```

2024-11-14 14:46 UTC, susilnem commented on Dockerfile
> +ENV PYTHONUNBUFFERED=1
```suggestion
ENV PYTHONUNBUFFERED 1
```

2024-11-15 03:54 UTC, thenav56 approved these changes
LGTM

2024-11-15 04:15 UTC, merged