Feature/gdacs transformation
IFRCGo/montandon-etl pull request #61
Opened 2024-12-26 09:37 UTC by Rup-Narayan-Rajbanshi

Addresses
  - https://github.com/IFRCGo/montandon-etl/issues/38

Depends on
- (https://github.com/IFRCGo/montandon-etl/pull/4)

## Changes
- Integrate transformation for gdacs using pystac-monty library

## This PR doesn't introduce any:

- [ ] temporary files, auto-generated files or secret keys
- [ ] n+1 queries
- [ ] flake8 issues
- [ ] `print`
- [ ] typos
- [ ] unwanted comments

## This PR contains valid:

- [ ] tests
- [ ] permission checks (tests here too)
- [ ] translations

2025-01-08 11:17 UTC, frozenhelium commented on apps/common/models.py
> +        CLUSTER = 2, _("Cluster")
Let's revisit this

2025-01-08 11:57 UTC, frozenhelium reviewed
Also let's remove/rename/squash WIP commits

2025-01-08 12:09 UTC, frozenhelium commented on apps/etl/tasks.py
Looks like this is specific to GDACS and should be namespaced accordingly

2025-01-08 12:09 UTC, frozenhelium commented on apps/etl/transformer.py
Looks like this is GDACS specific and should be namespaced properly

2025-01-08 12:16 UTC, frozenhelium commented on README.md
> +    ```
We should also include instruction on setting up the `libs/pystac-monty` submodule

2025-01-08 12:48 UTC, frozenhelium commented on README.md
> +    ```
`git submodule update --init --recursive`

2025-01-10 09:11 UTC, Rup-Narayan-Rajbanshi commented
> Also let's remove/rename/squash WIP commits

@frozenhelium Dai, We will be squash all the commit into single commit in the end. So, these commits will not be a problem.

2025-01-10 09:16 UTC, Rup-Narayan-Rajbanshi commented on apps/etl/tasks.py
@frozenhelium I realized this when adding another source i.e Glide. So i am planning to make a folder for each source and add extract, transform, load files in it like you are in Desinvantar. Also update this file to include all the ETLs for each source. What do you say?

2025-01-10 09:16 UTC, Rup-Narayan-Rajbanshi commented on apps/etl/transformer.py
https://github.com/IFRCGo/montandon-etl/pull/61#discussion_r1910052085

2025-01-13 06:42 UTC, thenav56 requested changes
Phase-01 PR Review

2025-01-13 06:42 UTC, thenav56 commented on Dockerfile
> +COPY libs /code/libs
Let's add a NOTE, on why we have this here.

2025-01-13 06:42 UTC, thenav56 commented on apps/common/models.py
> +class UserResource(models.Model):
Let's change this to Resource

Also, add UserResource and use if a user mutate any idea in the future.. make sure to add created_by and modifed_by also

2025-01-13 06:42 UTC, thenav56 commented on apps/etl/extract.py
> +                raise ObjectDoesNotExist("ExtractionData object with ID {ext_object_id} not found")
```suggestion
                raise ObjectDoesNotExist(f"ExtractionData object with ID {ext_object_id} not found")
```

2025-01-13 06:42 UTC, thenav56 commented on apps/etl/extract.py
> +                    "resp_text": response.text,
Add TODO, there might not be always text.

2025-01-13 06:42 UTC, thenav56 commented on apps/etl/extract.py
> +            if response.status_code != 200:
Let's remove raise and use basic if/else in linear order

2025-01-13 06:42 UTC, thenav56 commented on apps/etl/models.py
> +class HazardType(models.TextChoices):
Add TODO: User IntegerChoices and add mapping for import/export

2025-01-13 06:42 UTC, thenav56 commented on apps/etl/models.py
> +    url = models.URLField(verbose_name=_("url"), blank=True)
Let's confirm if we need blank=True

Also, confirm for other IntegerField fields

2025-01-13 06:42 UTC, thenav56 commented on apps/etl/models.py
> +    file_hash = models.CharField(
Add TODO: change to resp_data -> response_file

```suggestion
    response_file = models.FileField(verbose_name=_("response data"), upload_to="source_raw_data/", blank=True, null=True)
    response_file_hash = models.CharField(
```

2025-01-13 06:42 UTC, thenav56 commented on apps/etl/models.py
> +    resp_data_type = models.CharField(verbose_name=_("response data type"), blank=True)
```suggestion
    resp_other_type = models.CharField(verbose_name=_("response data type"), blank=True)
```

2025-01-13 06:42 UTC, thenav56 commented on apps/etl/models.py
> +    resp_text = models.TextField(verbose_name=_("response data in case failure occurs"), blank=True)
```suggestion
    resp_error_text = models.TextField(verbose_name=_("response data in case failure occurs"), blank=True)
```

2025-01-13 06:42 UTC, thenav56 commented on apps/etl/models.py
> +    parent = models.ForeignKey("self", on_delete=models.PROTECT, null=True, blank=True, related_name="child_extraction")
```suggestion
    parent = models.ForeignKey("self", on_delete=models.PROTECT, null=True, blank=True, related_name="child_extractions")
```

2025-01-13 06:42 UTC, thenav56 commented on apps/etl/models.py
> +    source_validation_status = models.IntegerField(
```suggestion
    validation_status = models.IntegerField(
```

2025-01-13 06:42 UTC, thenav56 commented on apps/etl/models.py
> +    content_validation = models.TextField(verbose_name=_("validation status fail reason"), blank=True)
```suggestion
    validation_error = models.TextField(verbose_name=_("validation status fail reason"), blank=True)
```

2025-01-13 06:42 UTC, thenav56 commented on apps/etl/models.py
> +    revision_id = models.ForeignKey(
Let's brainstorm naming for this.. Something like

same_existing_extraction?

2025-01-13 06:42 UTC, thenav56 commented on apps/etl/models.py
Let's visit on the folder structure with something like this

```
apps/extraction
    - ...
    - models.py
    - sources/
        - base
            - extraction.py
        - gdacs
            - extraction.py
            - validators.py
        - glide
            - ...

apps/transform
    - ...
    - models.py
    - sources/
        - base.py
        - gdacs.py
        - glide.py


apps/load
    - ...
    - sources/
        - base.py
        - gdacs.py
        - glide.py
```

2025-01-13 06:42 UTC, thenav56 commented on apps/etl/transformer.py
> +def transform_event_data(data):
Add gdacs here

2025-01-13 06:42 UTC, thenav56 commented on apps/etl/transformer.py
> +    gdacs_instance = ExtractionData.objects.get(id=data["extraction_id"])
Add filter here for gdacs

2025-01-13 06:42 UTC, thenav56 commented on apps/etl/transformer.py
> +        raise
User direct `gdacs_instance.resp_data.read()`, this is handled by the backend storage class.
https://docs.djangoproject.com/en/5.1/ref/files/storage/

2025-01-15 06:32 UTC, samshara approved these changes

2025-01-15 06:32 UTC, merged